### ISSUE TITLE
Rewrite in Typescript

### ISSUE THREAD

**Issue by HypernovaTX** [mailcharts/animated-gif-detector#6]
### Request
Permission to publish my own NPM package that borrowed some of the codes but in Typescript. 

### Description
I have found good use of this for my personal project but I found out there is no typescript support. However, I modified the codes in my own projects that they can handle typescript with ease. I am not sure what is the stance of Mailcharts on this.

**Comment by tbuchok** [comment]
hi @HypernovaTX - thanks a lot for reaching out!

this repo is open source and you’re free to follow either (or both) of the below paths:

- issue a PR with the TS updates you recommend
  - note: _this repo is not under active development, so this may take some time for our team to review, accept, and then bump the npm package_
- fork this repository and make the edits however you’d like to proceed - it’s completely up to you
  - if you’d then like to publish that fork under a different npm module name, you’re also free to do so

keep us posted on your progress!

**Comment by HypernovaTX** [comment]
> hi @HypernovaTX - thanks a lot for reaching out!
> 
> this repo is open source and you’re free to follow either (or both) of the below paths:
> 
> * issue a PR with the TS updates you recommend
>   
>   * note: _this repo is not under active development, so this may take some time for our team to review, accept, and then bump the npm package_
> * fork this repository and make the edits however you’d like to proceed - it’s completely up to you
>   
>   * if you’d then like to publish that fork under a different npm module name, you’re also free to do so
> 
> keep us posted on your progress!

Thanks Tom! I have finished updating it to Typescript and created a new NPM package off the branch:
- [Branch](https://github.com/HypernovaTX/is-animated-gif)
- [NPM](https://www.npmjs.com/package/is-animated-gif)
